101-Coconsulting/TC3005B.501-Frontend

- src/components/InputField.astro
- src/styles/global.css
- src/types/input.ts
This PR introduces the following changes to the `InputField` component:
Related to #28, closes #28 
This component supports optional labels, input types, placeholder, required and disabled states, as well as error handling with accessible markup. Uses Tailwind + global custom properties.
> 5 sub task input field design

- src/assets/sign-in.svg
- src/components/SideBarButton.astro
- src/components/Sidebar.astro
- src/types/sidebar.ts
- PR is linked to an issue: #11 (Sub-Task: SideBar Design) and #13 
- PR is from feature branch created from the `development` branch.
- PR is to the `development` branch.
- `git` conventional commits.
- Adds a reusable sidebar component that renders dynamic menu items based on user roles (`SOLICITANTE`, `AUTORIZADOR`).
- Uses TypeScript with explicit typing for `Props`, `UserRole`, and `MenuItem`.
- Implements conditional styling to highlight the active route.
- TailwindCSS classes applied for styling consistency with the rest of the app.
- Component matches UI design and follows team conventions.
None
Closes #11 and #13
> 11 sub task sidebar design

- src/components/ApplicantRequest.astro
- src/components/Button.astro
- src/datadummy/viajesSolicitante.json
- src/pages/dashboard.astro
- tsconfig.json
Creation and model of the applicant dashboard to summarize their requests
- #14
> 14 task applicant create dashboard

- astro.config.mjs
- package.json
- pnpm-lock.yaml
- src/components/Modal.tsx
- src/components/ModalWrapper.tsx
- src/config/modal.ts
- tsconfig.json
This Pull Request introduces a reusable and accessible `Modal` component for the project, supporting multiple message types including **confirmation, warning, error, and success**.
The modal includes customizable content and styling based on type, and integrates cleanly with Tailwind CSS for consistent UI. It also includes a lightweight `ModalWrapper` component for local testing and demonstration purposes.
> 8 sub task modal dialogs design

- src/components/PageHeader.astro
- src/layouts/HeaderLayout.astro
- src/pages/user-profile.astro
- src/pages/userProfile.astro
Implementation of the screen belonging to the user role that allows a complete display of the profile data related to the logged-in account
N/A
N/A
> 38 implement user profile data display page

- src/components/RequestDetail.astro
- src/datadummy/requestHistory.json
This PR completes the full implementation of the **User - Complete Request View** feature.  
It allows applicants or authorized users to visualize a detailed travel request.
The detailed view includes:
- Applicant information: `name`, `company`, `department`, and `email`.
- Travel details: `destination`, `date`, `transportation`, `accommodation`, `purpose`.
- Current status of the request: `Aprobado`, `Pendiente`, or `Rechazado`.
- Additional comments or observations (if available).
- Styled and responsive layout using TailwindCSS.
- Dummy data updated to reflect additional request details for integration with the UI.
✅ Fully aligned with the acceptance criteria from issue #16.  
✅ UI spacing, typography, and structure were adjusted based on design feedback.
None
Closes #16
> 16 task user   complete request view

- src/components/RequestApproval.astro
- src/pages/application-approval.astro
- src/pages/autorizar-solicitud/[id].astro
This PR introduces the Application Approval screen:
Related to #19, closes #19 
Initial implementation of the travel request approval screen with:
- Travel details display section
- Authorization/rejection buttons
- Confirmation dialogs
- Responsive layout
- Uses Tailwind + global custom properties.
> 19 task authorizer   application approval screen

- .github/codeql/codeql-config.yml
- .github/workflows/codeql-analysis.yml
This pull request integrates the configuration for the CodeQL scanner to analyze the code in Frontend for any vulnerabilities.
None
None
> CodeQL configuration frontend

- src/components/DataTable.astro
- src/components/TableFallback.astro
- src/components/TableHeader.astro
- src/components/TableRow.astro
sub task requests list design content tables
> 10 sub task requests list design content tables

- README.md
The repository will include a _Getting Started_ section with instructions on how to install the repository locally, install dependencies, run the frontend, and configure it to show the various available screens and dashboards.
_N/A_
_N/A_
> 76 task getting started instructions

- src/components/ExpensesValidation.astro
- src/data/get-expense-validations.json
- src/pages/comprobar-gastos/[id].astro
This pr implements the checkout page for the receips atached to an Expenses Comprobation.
#67 
#67
> 66 task accountspayable   download and verify applicants uploaded receipts

- src/components/Button.tsx
- src/components/ExpensesValidation.astro
- src/components/ReceiptActions.tsx
- src/components/RequestDetail.astro
- src/components/TableFallback.astro
- src/pages/comprobar-gastos/[id].astro
- src/utils/getStatus.js
This PR introduces the receipt-level approval and rejection functionality for the **Accounts Payable** module.
- Added `ReceiptActions` React component:
- Provides individual `Approve` and `Reject` buttons per receipt.
- Includes a confirmation modal to prevent accidental actions.
- Implemented status mapping with `getStatusProps` utility:
- Translates internal statuses into user-friendly labels with appropriate styling.
- Developed logic to evaluate and update the **overall status of the request** based on the state of all individual receipts (pending, approved, declined).
- Integrated UI with TailwindCSS components for visual clarity.
This feature ensures that the Accounts Payable team can review and approve expenses at a granular level, while keeping the parent request’s status …
> 67 task accountspayable   approve or reject submitted receipts and control expense request status

- src/pages/comprobacion-gastos.astro
- src/pages/comprobar-solicitud/[id].astro
- src/views/ApplicantView.astro
This pr implements the section to submit receipts and invoices.
#64 
#64
> 64 task applicant - submit receipts and invoices with detailed information

- src/views/AccountsPayableView.astro
_Now AccountsPayable dahboard has the two different modules to display quote and check_
N/A
#73
> 68 task accountspayable create module to display pending verifications and reimbursements

- src/pages/perfil-usuario.astro
Aliign user profile data with database structure 
N/A
> fix: align user profile data with database structure

- README.md
_Updating some `README` features_
_#76_
_N/A_
> docs: update README stack and shields

- src/components/RequestDraft.astro
- src/pages/editar-solicitud/[id].astro
- src/pages/solicitudes-draft.astro
- src/types/menu-config.ts
_Add draft requests page and update edit page and menu config_
> 93 task chore add draft requests tab to sidebar

- CHANGELOG.md
- package.json
- src/components/Modal.tsx
- src/components/ModalWrapper.tsx
- src/components/RequestDraft.astro
- src/pages/cotizaciones.astro
- src/pages/crear-solicitud.astro
- src/types/menu-config.ts
- src/views/ApplicantView.astro
_Performed general bug review and cleanup for release v0.2.0. Added structured changelog entries summarizing new features, changes, and fixes._
> 99 task chore   release audit and bug review

- src/views/AccountsPayableView.astro
_Now AccountsPayable dahboard has the two different modules to display quote and check_
N/A
#73
> 68 task accountspayable   create module to display pending verifications and reimbursements

- .env.example
- astro.config.mjs
- pnpm-lock.yaml
- src/components/CancelRequestModal.tsx
- src/components/CheckExpenses.astro
- src/components/Modal.tsx
- src/components/ModalWrapper.tsx
- src/components/RequestDetail.astro
- src/components/RequestDraft.astro
- src/components/RequestsLists/AuthRequestsList.tsx
- src/components/Table/DataTable.tsx
- src/data/cookies.ts
- src/data/get-expense-validations-2.json
- src/data/get-expense-validations-3.json
- src/pages/comprobaciones.astro
- src/pages/comprobar-gastos.astro
- src/pages/comprobar-gastos/[id].astro
- src/pages/crear-solicitud.astro
- src/pages/dashboard.astro
- src/pages/detalles-solicitud/[id].astro
- src/utils/apiClient.ts
- src/views/ApplicantView.astro
_Allow Frontend to communicate to Backend API fetching DataBase scheme_
> 113 task chore   refactor frontend structure for backend integration

- src/components/CheckExpenses.astro
- src/components/ExpensesForm.astro
- src/components/RequestCard.astro
- src/components/RequestDraft.astro
- src/components/RequestSection.astro
- src/data/attend-travel-request.json
- src/data/authorize-travel-request.json
- src/data/create-expense-validation.json
- src/data/decline-travel-request.json
- src/data/get-alerts.json
- src/data/get-completed-requests.json
- src/data/get-expense-validations-2.json
- src/data/get-expense-validations.json
- src/data/get-travel-request.json
- src/data/get-travel-requests.json
- src/data/get-user-request.json
- src/data/get-user-requests-2.json
- src/pages/comprobaciones.astro
- src/pages/comprobar-gastos.astro
- src/pages/comprobar-solicitud/[id].astro
- src/pages/recibos-subidos/[id].astro
- src/pages/solicitudes-draft.astro
- src/pages/subir-comprobante/[id].astro
- src/views/AccountsPayableView.astro
- src/views/AdminView.astro
- src/views/AuthorizerView.astro
> 64 task applicant   submit receipts and invoices with detailed information

- src/components/History.tsx
- src/components/RequestsLists/AuthRequestsList.tsx
- src/data/cookies.ts
- src/pages/atender-solicitud/[id].astro
- src/pages/comprobaciones.astro
- src/pages/historial.astro
Integrate the API with the following screens:
N/A
#102 
--------------------
> [!WARNING]
> The page "atender solicitud" was not tested due to an issue with the static routes. However, following @Porto1090 s instructions, we pushed the changes and hoped for the best...
> 104 sub task full stack integration team a

- src/components/RequestCard.astro
- src/pages/autorizaciones.astro
- src/views/TravelAgencyView.astro
Connection of Cotizaciones and TravelAgencyView with backend
#102
> 111 sub task full stack integration team h

- src/views/AccountsPayableView.astro
_Outline what the Pull Request achieves, and the effect it will have upon being merged to the development branch._
_List dependent issues which could start to be worked on once this PR is merged._
_List affected issues which would require merging from `development` once this PR is merged._
> Featured: Endpoints added to AccountsView

- src/components/Typography.astro
- src/pages/atenciones.astro
- src/views/AuthorizerView.astro
- [X ] Use **only** `git` conventional commits of type `style`, `docs`, `refactor`, or `chore`.
Integrate the screens described on issue #110 
#102 
#102
> feat: integrate backend API data in atenciones page

- src/components/RequestApproval.astro
- src/components/TravelRequestActionWrapper.tsx
- src/data/cookies.ts
Conection of the Authorizer with the backend 
#106
This task was work in one same computer with @A09271
> feat: added TravelRequestActionWrapper and fixed RequestApproval

- astro.config.mjs
- package.json
- pnpm-lock.yaml
- src/components/LoginForm.tsx
- src/components/Messages.astro
- src/components/ModalWrapper.tsx
- src/components/PageHeader.astro
- src/components/RequestDraft.astro
- src/components/TravelRequestForm.tsx
- src/layouts/HeaderLayout.astro
- src/layouts/Layout.astro
- src/layouts/MainLayout.astro
- src/middleware.ts
- src/pages/atenciones.astro
- src/pages/atender-solicitud/[id].astro
- src/pages/autorizaciones.astro
- src/pages/autorizar-solicitud/[id].astro
- src/pages/completar-draft/[id].astro
- src/pages/comprobar-gastos/[id].astro
- src/pages/comprobar-solicitud/[id].astro
- src/pages/cotizaciones.astro
- src/pages/cotizar-solicitud/[id].astro
- src/pages/crear-solicitud.astro
- src/pages/detalles-solicitud/[id].astro
- src/pages/editar-solicitud/[id].astro
- src/pages/historial.astro
- src/pages/login.astro
- src/views/ApplicantView.astro
- tsconfig.json
_To be able to use a service published in the `pnpm run preview` it is necessary to have access to the `backend` cors and for that it is necessary to take into account the HTTP protocol being used and how it will be installed in the cloud._
> feat(build): enable production-ready configuration

- cypress/e2e/cancelRequest.cy.ts
This pull request adds a Cypress test that ensures the system, taking the role of an applicant, deletes a travel request before it passes through the first filter. 
No dependent issues linked to this PR 
No affected issues
> 156: Applicant travel cancellation Cypress test ( ID 104 )

- cypress/e2e/state_test.cy.js
> 167 sub task estado de solicitud id 107

- cypress/e2e/requestUpdate.cy.ts
This PR includes a Cypress test that confirms the "update Travel request" functionality
No dependent issues
No Affected issues
<!--
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
CHORE PR TEMPLATE END
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> feat: added cypress test to update a request as an applicant

- src/components/AdminUserForm.tsx
- src/pages/crear-usuario.astro
Fix token for Admin functionality
> fix: Add token for create and edit user

- cypress/e2e/mensajeError_camposVacios.cy.js
_Cypress test to show empty fields error message_
> Task 164: Cypress test to show empty fields error message

- src/components/AdminUserForm.tsx
- src/pages/editar-usuario/[id].astro
> fix: Fixes that where made in the cloud
